# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/ihuntgore/Users/Juan/Documents/proyectos/python/qtdesigner/practica1/views/vista_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 271)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txta_nombre = QtWidgets.QTextEdit(self.centralwidget)
        self.txta_nombre.setGeometry(QtCore.QRect(20, 90, 251, 51))
        self.txta_nombre.setObjectName("txta_nombre")
        self.lbl_nombre = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nombre.setGeometry(QtCore.QRect(20, 60, 191, 24))
        self.lbl_nombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.btn_saludar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_saludar.setGeometry(QtCore.QRect(290, 100, 115, 33))
        self.btn_saludar.setObjectName("btn_saludar")
        self.btn_sobre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sobre.setGeometry(QtCore.QRect(270, 190, 141, 41))
        self.btn_sobre.setObjectName("btn_sobre")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_nombre.setText(_translate("MainWindow", "Nombre"))
        self.btn_saludar.setText(_translate("MainWindow", "Saludar"))
        self.btn_sobre.setText(_translate("MainWindow", "Sobre la App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
