# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/ihuntgore/Users/Juan/Documents/proyectos/python/qtdesigner/practica1/views/vista_sobre_nosotros.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 271)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titulo.setGeometry(QtCore.QRect(0, 20, 421, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setStyleSheet("QLabel {\n"
"    color: rgb(7, 24, 255);\n"
"}")
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_cuerpo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cuerpo.setGeometry(QtCore.QRect(0, 40, 421, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_cuerpo.setFont(font)
        self.lbl_cuerpo.setStyleSheet("QLabel {\n"
"    color: black;\n"
"}")
        self.lbl_cuerpo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cuerpo.setWordWrap(True)
        self.lbl_cuerpo.setObjectName("lbl_cuerpo")
        self.btn_volver = QtWidgets.QPushButton(self.centralwidget)
        self.btn_volver.setGeometry(QtCore.QRect(290, 220, 115, 33))
        self.btn_volver.setObjectName("btn_volver")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_titulo.setText(_translate("MainWindow", "Sobre esta aplicacion"))
        self.lbl_cuerpo.setText(_translate("MainWindow", "Esta aplicacion no es más que un experimento para implementar modelo-vista-controlador y facilitar la programacion de aplicaciones grandes usando Qt Designer"))
        self.btn_volver.setText(_translate("MainWindow", "Volver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
